/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab6;

import java.util.HashMap;
import java.util.Map;
import javax.swing.*;

/**
 *
 * @author bassam
 */
public class Resize extends JDialog {

    private JTextField field1, field2;
    private String shape;
    private final Map<String, Double> properties = new HashMap<>();
    private final Shape resizedShape;

    /**
     * Creates new form Resize
     *
     * @param resizedShape
     *
     */
    public Resize(Shape resizedShape) {
        super();
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setModal(true);
        this.resizedShape = resizedShape;
        shapeType();
        setPageTitle();
        setPageLayout();
        setLayout(null);
        resize.setText("Resize " + shape);

    }

    private void shapeType() {
        if (resizedShape instanceof Circle) {
            shape = "circle";
        } else if (resizedShape instanceof Rectangle) {
            shape = "rectangle";
        } else if (resizedShape instanceof Square) {
            shape = "square";
        } else if (resizedShape instanceof LineSegment) {
            shape = "line segment";
        }
    }

    private void setPageTitle() {
        switch (shape) {
            case "line segment" ->
                setTitle("Resize Line Segment");
            case "circle" ->
                setTitle("Resize Circle");
            case "square" ->
                setTitle("Resize Square");
            default ->
                setTitle("Resize Rectangle");
        }
    }

    private void setPageLayout() {
        switch (shape) {
            case "square" -> {
                JLabel label = new JLabel("Enter Side Length");
                label.setBounds(40, 50, 100, 40);
                field1 = new JTextField();
                field1.setBounds(150, 50, 200, 40);
                add(label);
                add(field1);
            }
            case "rectangle" -> {
                JLabel label1 = new JLabel("Enter Width");
                JLabel label2 = new JLabel("Enter Height");
                label1.setBounds(40, 20, 100, 40);
                label2.setBounds(40, 80, 100, 40);
                field1 = new JTextField();
                field1.setBounds(150, 20, 200, 40);
                field2 = new JTextField();
                field2.setBounds(150, 80, 200, 40);
                add(label1);
                add(label2);
                add(field1);
                add(field2);
            }
            case "circle" -> {
                JLabel label = new JLabel("Enter Radius");
                label.setBounds(40, 50, 100, 40);
                field1 = new JTextField();
                field1.setBounds(150, 50, 200, 40);
                add(label);
                add(field1);
            }
            case "line segment" -> {
                JLabel label1 = new JLabel("Enter X2");
                JLabel label2 = new JLabel("Enter Y2");
                label1.setBounds(40, 20, 100, 40);
                label2.setBounds(40, 80, 100, 40);
                field1 = new JTextField();
                field1.setBounds(150, 20, 200, 40);
                field2 = new JTextField();
                field2.setBounds(150, 80, 200, 40);
                add(label1);
                add(label2);
                add(field1);
                add(field2);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resize = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        resize.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.foreground"));
        resize.setText("Delete");
        resize.setOpaque(true);
        resize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(resize, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(resize, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resizeActionPerformed
        switch (shape) {
            case "line segment" -> {
                properties.put("endX", Double.valueOf(field1.getText()));
                properties.put("endY", Double.valueOf(field2.getText()));
            }
            case "circle" -> {
                properties.put("radius", Double.valueOf(field1.getText()));
            }
            case "square" -> {
                properties.put("side", Double.valueOf(field1.getText()));
            }
            case "rectangle" -> {
                properties.put("width", Double.valueOf(field1.getText()));
                properties.put("height", Double.valueOf(field2.getText()));
            }
        }
        resizedShape.setProperties(properties);
        dispose();
        setVisible(false);
    }//GEN-LAST:event_resizeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton resize;
    // End of variables declaration//GEN-END:variables
}
